

export const LIMITS = {

    MAX_PERSONAS_PER_PAGE: 20,
    MAX_CHATS_PER_PAGE: 20,
    MAX_CHARACTERS_PER_PAGE: 21,
    MAX_CATEGORIES_PER_PAGE: 15,
    MAX_TRENDING_CHARACTERS_PER_PAGE: 21,
    MAX_MESSAGES_PER_PAGE: 100,
    MAX_MESSAGES_IN_CHAT: 200,
    MAX_RAG_RESULTS: 5,
}